[package]
name = "revive-creature"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.4.1"
flate2 = "1.0"
failure = "0.1.8"
nom = { version = "7.0.0", features = ["alloc"] }